**Prerequisite**:

// not sure I'll need this driver
pip install py2neo 

pip install ipython-cypher

--data preloaded with kgraph-benchmark (not mandatory)

##Setup:##

In [1]:
%load_ext cypher

In [2]:
#from py2neo import Graph, authenticate, Node, Relationship

In [3]:
# global variables
user_pwd = ("neo4j","73cef53990")
port = "7004"
host = "bbpcb013.epfl.ch"
cypher_conn = 'http://' + user_pwd[0] + ':' + user_pwd[1] + '@' + host + ':' + port + '/db/data' 

print cypher_conn

http://neo4j:73cef53990@bbpcb013.epfl.ch:7004/db/data

In [4]:
#lost few hours on this one:
#For all magics, Python expands variables only when prefix with '$' (bash-style)!!!!
%cypher $cypher_conn

'Connected: http://neo4j:73cef53990@bbpcb013.epfl.ch:7004/db/data'

## Data Integrity QA Part-1: 

##Entity checks:
    * checks all labels and counts
    * checks Duplicate node entity (nodes with same UUID)
    * checks all disconnected nodes
    * checks nodes that do not have certain property or proprty value seems wrong

**QC: Report all Labels and entity count**

In [5]:
%%cypher $cypher_conn

match (n)
return distinct labels(n) as labels, count(*) as nb_occurence
order by nb_occurence desc

25 rows affected.

[[[u'DB_XREF', u'PLAN', u'_PLAN'], 1409],
 [[u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  1276],
 [[u'DB_XREF', u'MIME_TYPE', u'_MIME_TYPE'], 1276],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'], 992],
 [[u'DB_XREF', u'LOCATION', u'_LOCATION'], 569],
 [[u'ProvenanceGraphObject', u'AGENT', u'PERSON', u'_PERSON'], 554],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'], 426],
 [[u'DB_XREF', u'DOMAIN_TYPE', u'_DOMAIN_TYPE'], 426],
 [[u'DB_XREF', u'ENTITY_CLASS', u'_ENTITY_CLASS'], 417],
 [[u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  417],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SAMPLE', u'_SAMPLE'], 143],
 [[u'DB_XREF', u'SEX', u'_SEX'], 143],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'REGISTRATION', u'_REGISTRATION'],
  143],
 [[u'DB_XREF', u'SPECIES', u'_SPECIES'], 143],
 [[u'DB_XREF', u'STRAIN', u'_STRAIN'], 143],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'], 143],
 [[u'DB_XREF', u'SCALE', u'_SCALE'], 143],
 [[u'Ent'], 4],
 [[u'Entity'], 4],
 [[u'Act'], 4],
 [[u'Activity'], 3],
 [[u'ACTIVITY'], 1],
 [[u'ENTITY'], 1],
 [[u'Person'], 1],
 [[u'Dummy'], 1]]

**QC: Duplicate node's UUID**

In [6]:
%%cypher $cypher_conn

match (n) 
with n.uuid as nodeUUId, count(*) as nodeCount 
where nodeCount > 1 
return nodeUUId, nodeCount

117 rows affected.

[[u'90', 3],
 [u'111', 2],
 [u'99', 3],
 [u'57', 4],
 [u'84', 3],
 [u'78', 4],
 [u'63', 3],
 [u'105', 2],
 [u'30', 4],
 [u'45', 4],
 [u'39', 4],
 [u'66', 4],
 [u'51', 3],
 [u'87', 3],
 [u'2', 10],
 [u'72', 4],
 [u'5', 9],
 [u'48', 4],
 [u'33', 4],
 [u'69', 4],
 [u'27', 5],
 [u'54', 4],
 [u'12', 9],
 [u'60', 4],
 [u'8', 9],
 [u'15', 8],
 [u'42', 4],
 [u'110', 2],
 [u'36', 4],
 [u'98', 3],
 [u'21', 7],
 [u'119', 2],
 [u'71', 4],
 [u'92', 3],
 [u'113', 2],
 [u'18', 8],
 [u'86', 3],
 [u'24', 5],
 [u'107', 2],
 [u'74', 4],
 [u'101', 3],
 [u'89', 3],
 [u'95', 3],
 [u'53', 3],
 [u'68', 4],
 [u'80', 4],
 [u'41', 4],
 [u'35', 4],
 [u'83', 4],
 [u'104', 2],
 [u'62', 4],
 [u'56', 4],
 [u'7', 9],
 [u'77', 4],
 [u'59', 3],
 [u'17', 9],
 [u'50', 4],
 [u'44', 4],
 [u'23', 5],
 [u'38', 3],
 [u'65', 3],
 [u'47', 3],
 [u'4', 10],
 [u'26', 4],
 [u'115', 2],
 [u'11', 9],
 [u'32', 4],
 [u'14', 9],
 [u'82', 4],
 [u'97', 2],
 [u'20', 9],
 [u'29', 5],
 [u'118', 2],
 [u'103', 2],
 [u'85', 3],
 [u'79', 4],
 [u'112', 2],
 [u'70', 4],
 [u'64', 4],
 [u'91', 3],
 [u'106', 2],
 [u'46', 4],
 [u'94', 3],
 [u'52', 4],
 [u'109', 2],
 [u'73', 4],
 [u'67', 4],
 [u'88', 3],
 [u'100', 2],
 [u'34', 4],
 [u'6', 9],
 [u'28', 5],
 [u'40', 4],
 [u'55', 4],
 [u'49', 4],
 [u'61', 4],
 [u'76', 4],
 [u'9', 8],
 [u'43', 4],
 [u'22', 7],
 [u'58', 4],
 [u'16', 8],
 [u'37', 4],
 [u'19', 9],
 [u'3', 9],
 [u'10', 9],
 [u'31', 3],
 [u'25', 5],
 [u'93', 3],
 [u'114', 2],
 [u'108', 2],
 [u'13', 8],
 [u'81', 4],
 [u'75', 4],
 [u'96', 3],
 [u'102', 2],
 [None, 4688]]

**QC: Disconnected nodes**

In [7]:
%%cypher $cypher_conn

match (n)
where NOT n -- ()
return n

2 rows affected.

[[{u'name': u'alice'}], [{u'name': u'dummy'}]]

**QC: Nodes without a 'name' property**

In [8]:
%%cypher $cypher_conn

match (n)
where n.name is null
return n

0 rows affected.

[]

**QC: Nodes for which 'name' property has tiny size**

In [9]:
%%cypher $cypher_conn

match (n)
where size(n.name) < 3
return n

0 rows affected.

[]

## Data Integrity QA Part-2:

## Relationships
    * reports relationship types occurence
    * reports relationship type by entity (Label)
    * checks mandatory relationship between specific entity 
    * checks relationship without type (impossible: Neo4J enforces a single type defined for all relationship)
    * etc...

**QC: Report relationship types occurences**

In [32]:
%%cypher $cypher_conn

match (n)-[r]-(m) 
return type(r) as rela_type, count(*) as nb_occurence
order by nb_occurence desc

17 rows affected.

[[u'WAS_ASSOCIATED_WITH', 3390],
 [u'WAS_INFORMED_BY', 2818],
 [u'WAS_PLANNED_AS', 2818],
 [u'USED', 2816],
 [u'HAD_MIME_TYPE', 2552],
 [u'WAS_GENERATED_BY', 1980],
 [u'WAS_DERIVED_FROM', 1970],
 [u'WITH_REPRESENTATION', 1704],
 [u'HAD_LOCATION', 1138],
 [u'HAD_DOMAIN_TYPE', 852],
 [u'WAS_CLASSIFIED_BY', 834],
 [u'WAS_CLASSIFIED_AS', 754],
 [u'HAD_SPECIES', 286],
 [u'HAD_SEX', 286],
 [u'HAD_STRAIN', 286],
 [u'HAD_SCALE', 286],
 [u'ASSOCIATED_WITH', 2]]

**QC: Report relationship type by entity**

In [33]:
%%cypher $cypher_conn

match (n)-[r]->(m) 
return labels(n) as source, type(r) as type, labels(m) as target, count(*) as nb_occurence
order by nb_occurence desc

30 rows affected.

[[[u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  u'HAD_MIME_TYPE',
  [u'DB_XREF', u'MIME_TYPE', u'_MIME_TYPE'],
  1276],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  u'WAS_ASSOCIATED_WITH',
  [u'ProvenanceGraphObject', u'AGENT', u'PERSON', u'_PERSON'],
  992],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  u'WAS_INFORMED_BY',
  [u'ProvenanceGraphObject', u'ACTIVITY', u'REGISTRATION', u'_REGISTRATION'],
  992],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  u'WAS_PLANNED_AS',
  [u'DB_XREF', u'PLAN', u'_PLAN'],
  992],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  u'WITH_REPRESENTATION',
  [u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  852],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  u'USED',
  [u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'],
  568],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  u'HAD_DOMAIN_TYPE',
  [u'DB_XREF', u'DOMAIN_TYPE', u'_DOMAIN_TYPE'],
  426],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  u'HAD_LOCATION',
  [u'DB_XREF', u'LOCATION', u'_LOCATION'],
  426],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  u'WAS_DERIVED_FROM',
  [u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'],
  426],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  u'WAS_GENERATED_BY',
  [u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  426],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  u'USED',
  [u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  423],
 [[u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  u'WAS_GENERATED_BY',
  [u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  422],
 [[u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  u'WAS_ASSOCIATED_WITH',
  [u'ProvenanceGraphObject', u'AGENT', u'PERSON', u'_PERSON'],
  417],
 [[u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  u'WAS_DERIVED_FROM',
  [u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  417],
 [[u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  u'WAS_INFORMED_BY',
  [u'ProvenanceGraphObject', u'ACTIVITY', u'REGISTRATION', u'_REGISTRATION'],
  417],
 [[u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  u'WAS_PLANNED_AS',
  [u'DB_XREF', u'PLAN', u'_PLAN'],
  417],
 [[u'DB_XREF', u'ENTITY_CLASS', u'_ENTITY_CLASS'],
  u'WAS_CLASSIFIED_BY',
  [u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  417],
 [[u'ProvenanceGraphObject', u'ACTIVITY', u'REGISTRATION', u'_REGISTRATION'],
  u'WAS_ASSOCIATED_WITH',
  [u'ProvenanceGraphObject', u'AGENT', u'PERSON', u'_PERSON'],
  286],
 [[u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  u'USED',
  [u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  269],
 [[u'ProvenanceGraphObject', u'ENTITY', u'REPRESENTATION', u'_REPRESENTATION'],
  u'WAS_CLASSIFIED_AS',
  [u'DB_XREF', u'ENTITY_CLASS', u'_ENTITY_CLASS'],
  236],
 [[u'ProvenanceGraphObject',
   u'ACTIVITY',
   u'CLASSIFICATION',
   u'_CLASSIFICATION'],
  u'USED',
  [u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  148],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'],
  u'HAD_SEX',
  [u'DB_XREF', u'SEX', u'_SEX'],
  143],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SAMPLE', u'_SAMPLE'],
  u'HAD_LOCATION',
  [u'DB_XREF', u'LOCATION', u'_LOCATION'],
  143],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'],
  u'HAD_SPECIES',
  [u'DB_XREF', u'SPECIES', u'_SPECIES'],
  143],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SAMPLE', u'_SAMPLE'],
  u'HAD_SCALE',
  [u'DB_XREF', u'SCALE', u'_SCALE'],
  143],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'],
  u'HAD_STRAIN',
  [u'DB_XREF', u'STRAIN', u'_STRAIN'],
  143],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SAMPLE', u'_SAMPLE'],
  u'WAS_DERIVED_FROM',
  [u'ProvenanceGraphObject', u'ENTITY', u'SPECIMEN', u'_SPECIMEN'],
  142],
 [[u'ProvenanceGraphObject', u'ENTITY', u'SAMPLE', u'_SAMPLE'],
  u'WAS_GENERATED_BY',
  [u'ProvenanceGraphObject', u'ACTIVITY', u'EXPERIMENT', u'_EXPERIMENT'],
  142],
 [[u'ProvenanceGraphObject', u'ENTITY', u'OBSERVATION', u'_OBSERVATION'],
  u'WAS_CLASSIFIED_AS',
  [u'DB_XREF', u'ENTITY_CLASS', u'_ENTITY_CLASS'],
  141],
 [[u'ACTIVITY'], u'ASSOCIATED_WITH', [u'ENTITY'], 1]]

**QC: Check mandatory relationship**

In [42]:
%%cypher $cypher_conn

//Activity without Agent ? 
match (a:ACTIVITY)
optional match (a)-[r:WAS_ASSOCIATED_WITH]->(g:AGENT) 
with a,g
where r is null
return a

1 rows affected.

[[{u'name': u'dummy Activity'}]]

In [ ]:
# other mandatory relationships (to validate)
# Experiment without Agent? 
# Registration without Person?
#

________________________________________

##Script validation ....##

In [17]:
%%cypher $cypher_conn

//create a detached 'dummy Activity'
create (a:ACTIVITY {name: 'dummy Activity'} ) 
return a

In [15]:
%%cypher $cypher_conn

create (e:ENTITY {name : 'dummy Entity'}) 
return e

SyntaxError: invalid syntax (<ipython-input-15-bc93e7301fff>, line 2)

In [ ]:
#attach my 'dummy Activity' to a 'dummy Entity'
%%cypher $cypher_conn

match (a:ACTIVITY), (e:ENTITY)
where a.name = 'dummy Activity' and e.name = 'dummy Entity'
create (a)-[r:ASSOCIATED_WITH]->(e)
return r

In [ ]:
#now I should no longer have any disconnected node
%%cypher $cypher_conn
match (n)
where NOT n -- ()
return n

Adding a 'disconnected' Activity